In [1]:
!pip install numpy

     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.9 kB 320.0 kB/s eta 0:00:01
     -------------------------------------- 60.9/60.9 kB 641.1 kB/s eta 0:00:00
   ---------------------------------------- 0.0/13.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/13.0 MB 1.9 MB/s eta 0:00:07
   ---------------------------------------- 0.1/13.0 MB 1.4 MB/s eta 0:00:09
    --------------------------------------- 0.2/13.0 MB 1.8 MB/s eta 0:00:08
   - -------------------------------------- 0.3/13.0 MB 2.0 MB/s eta 0:00:07
   - -------------------------------------- 0.5/13.0 MB 2.2 MB/s eta 0:00:06
   - -------------------------------------- 0.6/13.0 MB 2.3 MB/s eta 0:00:06
   -- ------------------------------------- 0.8/13.0 MB 2.4 MB/s eta 0:00:06
   -- ------------------------------------- 0.9/13.0 MB 2.6 MB/s eta 0:00:05
   --- ------------------------------------ 1.1/13.0 MB 2.6 MB/s eta 0:00:05
   --


[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
import time

In [6]:
# This function provides a comprehensive summary of a numpy array's properties
# It displays the array's dimensional structure, shape, total number of elements, and data type
def describe(arr: np.ndarray) -> None:    
    """Prints out the summary of an array"""
    print(f'dimension: {arr.ndim}')  # Shows the number of axes/dimensions of the array (1D, 2D, 3D, etc.)
    print(f'shape: {arr.shape}')    # Shows the size of each dimension as a tuple (e.g., (4,) for 1D array with 4 elements)
    print(f'size: {arr.size}')      # Shows the total number of elements in the array
    print(f'dtype: {arr.dtype}')    # Shows the data type of elements stored in the array (int64, float64, etc.)

In [9]:
# Create two sample lists for demonstration
# list1 contains integers from 1 to 6
# list2 contains integers from 4 to 9

list1 = [1,2,3,4,5,6]
list2 = [4,5,6,7,8,9]

In [10]:
# Convert a tuple to a numpy array
# This demonstrates numpy array creation from tuple data
arr1 = np.array((1,2,3,4))

print(arr1)
describe(arr1)

[1 2 3 4]
dimension: 1
shape: (4,)
size: 4
dtype: int64


In [ ]:
# Create a 2D numpy array from existing lists
# This demonstrates creating a multi-dimensional array by combining list1, list2, and list1 again
# The resulting array will have shape (3, 6) - 3 rows and 6 columns
arr2=np.array([list1,list2,list1], dtype=np.float64)

print(arr2)
describe(arr2)

[[1 2 3 4 5 6]
 [4 5 6 7 8 9]
 [1 2 3 4 5 6]]
dimension: 2
shape: (3, 6)
size: 18
dtype: int64


In [ ]:
# Create a 1D/2D/3D/etc... numpy array filled with ones using np.ones()
# np.ones() is a numpy method that creates an array of specified shape filled with the value 1
# You can specify the shape, data type, and other parameters to customize the array
# This demonstrates creating an array with a specific shape and data type
# In this example, The array will have shape (2,3) with all elements initialized to 1
# Using int64 data type for integer values
arr3=np.ones(shape=(2,3), dtype=np.int64)

print(arr3)
describe(arr3)

[[1 1 1]
 [1 1 1]]
dimension: 2
shape: (2, 3)
size: 6
dtype: int64


In [ ]:
# Create a 1D/2D/3D/etc... numpy array filled with zeros using np.zeros()
# np.zeros() is a numpy method that creates an array of specified shape filled with the value 0
# You can specify the shape, data type, and other parameters to customize the array
# This demonstrates creating an array with a specific shape and data type
# In this example, The array will have shape (2,4) with all elements initialized to 0
# Using double data type for floating-point values
arr4=np.zeros(shape=(2,4),dtype=np.double)

print(arr4)
describe(arr4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
dimension: 2
shape: (2, 4)
size: 8
dtype: float64


In [ ]:
# Create a 1D numpy array with sequential values using np.arange()
# np.arange() is a numpy method that creates an array with evenly spaced values within a given interval
# You can specify start, stop, and step parameters to customize the sequence
# This demonstrates creating an array with sequential integers from 0 to 9
# In this example, np.arange(10) creates an array with values [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
arr5=np.arange(10)

print(arr5)
describe(arr5)

[0 1 2 3 4 5 6 7 8 9]
dimension: 1
shape: (10,)
size: 10
dtype: int64


In [ ]:
# Create a 1D numpy array with evenly spaced values using np.linspace()
# np.linspace() is a numpy method that creates an array with a specified number of evenly spaced values over a given interval
# You can specify start, stop, and num parameters to customize the sequence
# This demonstrates creating an array with 10 evenly spaced values from 0 to 30
# In this example, np.linspace(0,30,10) creates an array with 10 values evenly distributed between 0 and 30 (inclusive)
arr6=np.linspace(0,30,10)

print(arr6)
describe(arr6)

[ 0.          3.33333333  6.66666667 10.         13.33333333 16.66666667
 20.         23.33333333 26.66666667 30.        ]
dimension: 1
shape: (10,)
size: 10
dtype: float64


In [33]:
# Create a 2D numpy array with random values using np.random.rand()
# np.random.rand() is a numpy method that creates an array of specified shape filled with random values from a uniform distribution over [0, 1)
# You can specify the shape as separate arguments to customize the array dimensions
# This demonstrates creating a 2x2 array with random floating-point values between 0 and 1
# In this example, np.random.rand(2,2) creates a 2D array with shape (2,2) filled with random numbers
arr7=np.random.rand(2,2)

print(arr7)
describe(arr7)

[[0.8264876  0.11554209]
 [0.30171435 0.72207295]]
dimension: 2
shape: (2, 2)
size: 4
dtype: float64


In [ ]:
# Reshape a 2D numpy array into a 1D array using np.reshape()
# np.reshape() is a numpy method that changes the shape of an array without changing its data
# The total number of elements must remain the same (original shape: 2x4 = 8 elements)
# This demonstrates converting arr4 from shape (2,4) to shape (8,) - flattening it into a 1D array
# In this example, arr4.reshape(8) converts the 2D array into a 1D array with 8 elements
arr8=arr4.reshape(8)

print(arr8)
describe(arr8)

[0. 0. 0. 0. 0. 0. 0. 0.]
dimension: 1
shape: (8,)
size: 8
dtype: float64


In [ ]:
# Create a numpy array with ones using np.ones_like()
# np.ones_like() is a numpy method that creates an array of ones with the same shape and data type as the input array
# This is useful when you want to create a new array that matches the dimensions of an existing array
# In this example, np.ones_like(arr8) creates an array with the same shape as arr8 (1D with 8 elements) filled with 1s
# The data type will also match arr8's data type (float64)
arr9=np.ones_like(arr8)

print(arr9)
describe(arr9)

[1. 1. 1. 1. 1. 1. 1. 1.]
dimension: 1
shape: (8,)
size: 8
dtype: float64


In [ ]:
# Create a numpy array filled with a specific value using np.full()
# np.full() is a numpy method that creates an array of specified shape filled with a given fill_value
# You can specify the shape, fill_value, and data type to customize the array
# This demonstrates creating a 3D array with shape (2,2,6) where all elements are set to 8
# In this example, np.full(shape=(2,2,6), fill_value=8) creates a 3D array with 24 total elements (2*2*6), all set to 8
arr10=np.full(shape=(2,2,6), fill_value=8)

print(arr10)
describe(arr10)

[[[8 8 8 8 8 8]
  [8 8 8 8 8 8]]

 [[8 8 8 8 8 8]
  [8 8 8 8 8 8]]]
dimension: 3
shape: (2, 2, 6)
size: 24
dtype: int64


In [ ]:
# Create a 2D identity matrix using np.eye()
# np.eye() is a numpy method that creates a 2D identity matrix with ones on the main diagonal and zeros elsewhere
# You can specify N (number of rows/columns) to create an NxN square identity matrix
# This is commonly used in linear algebra operations and matrix computations
# In this example, np.eye(N=5) creates a 5x5 identity matrix with 1s on the diagonal and 0s elsewhere
arr11=np.eye(N=5)

print(arr11)
describe(arr11)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
dimension: 2
shape: (5, 5)
size: 25
dtype: float64


In [ ]:
#Arithmetic Array Operation using Numpy

# We'll create two arrays 'a' and 'b' and show how numpy performs element-wise operations
# Array 'a' contains sequential integers from 1 to 5
# Array 'b' contains alternating 1s and 0s, which is useful for demonstrating multiplication and division effects
a=np.array([1,2,3,4,5])
b=np.array([1,0,1,0,1])

print(f'a= {a}, and b= {b}')

a= [1 2 3 4 5], and b= [1 0 1 0 1]


In [ ]:
print('a+b: ',a+b)  # Element-wise Addition
print('a-b: ',a-b)  # Element-wise subtraction
print('a*b: ',a*b)  # Element-wise multiplication
print('b/a: ',b/a)  # Element-wise division (note: division by zero will result in inf)
print('a**b: ',a**b)  # Element-wise exponentiation (a raised to the power of b)
print('b%a: ',b%a)  # Element-wise modulo operation (remainder after division)

print('-'*70)

# Broadcasting operations with scalar values
# NumPy allows operations between arrays and scalar values by broadcasting the scalar to match the array shape
print('a+10: ',a+10)  # Add scalar to each element of array 
print('a-10: ',a-10)  # Subtract scalar from each element of array
print('a*10: ',a*10)  # Multiply each element of array by scalar
print('a/10: ',a/10)  # Divide each element of array by scalar
print('a**10: ',a**10)  # Raise each element of array to the power of a scalar

print('-'*70)


a+b:  [2 2 4 4 6]
a-b:  [0 2 2 4 4]
a*b:  [1 0 3 0 5]
b/a:  [1.         0.         0.33333333 0.         0.2       ]
a**b:  [1 1 3 1 5]
b%a:  [0 0 1 0 1]
----------------------------------------------------------------------
a+10:  [11 12 13 14 15]
a-10:  [-9 -8 -7 -6 -5]
a*10:  [10 20 30 40 50]
a/10:  [0.1 0.2 0.3 0.4 0.5]
a**10:  [      1    1024   59049 1048576 9765625]
----------------------------------------------------------------------


In [ ]:
# Create a column vector using numpy array
# This demonstrates creating a 2D array with shape (5,1) - a column vector
# The array 'c' contains values 1-5 arranged vertically in a single column
# This is useful for matrix operations and linear algebra computations
c=np.array([[1],[2],[3],[4],[5]])

print('c:',c)

c: [[1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
print('a.c: ', a.dot(c)) # dot product of a and c
print('-'*70,'\nStatistics over whole array (all elements)')

print('c min: ',c.min())  # Find the minimum value across all elements in the array
print('c max: ', c.max())  # Find the maximum value across all elements in the array
print('c sum: ',c.sum())  # Calculate the sum of all elements in the array
print('c mean: ',c.mean())  # Calculate the arithmetic mean (average) of all elements in the array


a.c:  [55]
---------------------------------------------------------------------- 
Statistics over whole array (all elements)
c min:  1
c max:  5
c sum:  15
c mean:  3.0


In [60]:
# Create a 2D numpy array with sample data for matrix operations
# This demonstrates creating a 4x2 array with paired values
# The array 'd' contains 4 rows and 2 columns with values ranging from 10 to 80
# This will be useful for demonstrating matrix operations and 2D array manipulations
d=np.array([[10,20],[30,40],[50,60],[70,80]])

print(d)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]


In [62]:
# Demonstrate axis-based statistical operations on 2D arrays
# axis=0 operates along columns (down the rows), axis=1 operates along rows (across the columns)

print('d min (columns): ',d.min(axis=0))  # Find minimum value in each column (compares values down each column)
print('d min (rows): ',d.min(axis=1))     # Find minimum value in each row (compares values across each row)

print('d max (columns): ',d.max(axis=0))  # Find maximum value in each column (compares values down each column)
print('d max (rows): ',d.max(axis=1))     # Find maximum value in each row (compares values across each row)

print('d sum (columns): ',d.sum(axis=0))  # Calculate sum of values in each column (adds values down each column)
print('d sum (rows): ',d.sum(axis=1))     # Calculate sum of values in each row (adds values across each row)

print('d mean (columns): ',d.mean(axis=0))  # Calculate mean of values in each column (averages values down each column)
print('d mean (rows): ',d.mean(axis=1))     # Calculate mean of values in each row (averages values across each row)

d min (columns):  [10 20]
d min (rows):  [10 30 50 70]
d max (columns):  [70 80]
d max (rows):  [20 40 60 80]
d sum (columns):  [160 200]
d sum (rows):  [ 30  70 110 150]
d mean (columns):  [40. 50.]
d mean (rows):  [15. 35. 55. 75.]
